### PR TITLE
Add support for aarch64/ppc64le

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Hi @conda-forge/bc! I think this PR is ready for review. Thanks!

**Comment by jaimergp** [comment]
Hi @conda-forge/core! Can anybody review this? This is the last dependency missing in order to try building `ambertools` for PPC. Thanks!

**Comment by isuruf** [comment]
@jaimergp, do you want to be a maintainer for this feedstock?

**Comment by jaimergp** [comment]
I wouldn't mind! Shall I add myself?

**Comment by isuruf** [comment]
Yes, I'll merge after that.

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Last commit was just a readme update.

**Pull request merged**
