### PR TITLE
Added missing compiler dependency

### LINKED ISSUE #3: This repo needs to depend on {{ compiler('c') }}

### PR DESCRIPTION
**Pull request by duncanmmacleod**
Fixes #3.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@conda-forge/bc, the build is failing on macOS due to a missing link to libfl (flex). I don't understand why this is required only now, and wasn't before; is the solution just to add a run dependency on `flex`?

**Comment by scopatz** [comment]
I'd say you should try adding the flex dependency and see if it works

**Comment by duncanmmacleod** [comment]
@scopatz, done in 76d905e, I was only hesitant because this used to work without that and I don't understand how the compiler magic changed things. But then, I don't understand the compiler magic at all...

**Comment by scopatz** [comment]
basically, deps that are linked against, need to be in host

**Comment by scopatz** [comment]
Also, would you like to please add yourself as a maintainer here, since the current maintainers seem to have abandoned this?

**Comment by duncanmmacleod** [comment]
@scopatz, I can do, but I have no idea what `bc` does, how to use it, or how to fix bugs. Apart from that, I'll do a great job.

Re: `host` section, do you mean that because the `flex` dependency used to be in `build` it wasn't an issue?

**Comment by scopatz** [comment]
> @scopatz, I can do, but I have no idea what bc does, how to use it, or how to fix bugs. Apart from that, I'll do a great job. 

hahah thanks! The story of conda-forge really...

> Re: host section, do you mean that because the flex dependency used to be in build it wasn't an issue?

Yeah, exactly

**Comment by scopatz** [comment]
@conda-forge-admin, please rerender

**Comment by scopatz** [comment]
The bot now needs to pick this up and rerender this.

**Pull request merged**
